# Language setting
language: node_js

# Version number
node_js:
  - 0.11
env:
  global:
  #Testing for user defined envs and secure envs
    - TEST=FOO
   
  matrix:
    - M1=ONE


git:
   submodules: false
build:
 

  ci:
   
    - node --version
    - lsb_release -a
    - docker --version
    - docker info
    - docker ps
 
resources:
  - name: sn-img-1
    type: image
    integration: ship-gcr
    pointer:
      sourceName: gcr.io/vidya-project/node1-img:master.33
      isPull: true
    seed:
      versionName: "latest"
  - name: ship-slack
    type: notification
    integration: ship-slack
    pointer:
      recipients:
        - "#rc-public"
        - "#rc-private"    
  - name: sn-gke-service-lb                               #required
    type: loadBalancer                          #required
    integration: ship-gcr  #Required for use in provision jobs
    pointer:
      sourceName: "xyz-scriptnull-local"  # the service name (metadata.name)
      method: ClusterIP # the service type Kubernetes default: ClusterIP
      clusterName: "cluster-1" # The namespace for the service
      region: "us-central1-a"
      namespace: "default"    # optional
    version:
      ports:
        - name: scriptnull-local-port-test # Required for multiple ports, must be a DNS_LABEL
          protocol: TCP  # Kubernetes default: TCP
          port: 8001     # Required.
          targetPort: 8002 # A number in 1-65535 or an "IANA_SVC_NAME"  This is the port to access the pod.
         # nodePort: <integer> # Port exposed on the node.  Kubernetes will auto-allocate by default.
      selector:
        new: scriptnull-local # Required. Labels to match the pod
  - name: newkubebastionloadbalancer
    type: loadBalancer
    integration: ship-kube
    pointer:
      sourceName: "xyz-kube-local-gen-bash-gen-12-bash"
      method: ClusterIP
      clusterName: "testrc" # The namespace for the service
      region: "us-west-2" #"europe-west1-b"
      namespace: "temp-namespace-f"
    version:
      ports:
        - name: kube-local-port  # Required for multiple ports, must be a DNS_LABEL
          protocol: TCP  # Kubernetes default: TCP
          port: 8001     # Required.
          targetPort: 8002 # A number in 1-65535 or an "IANA_SVC_NAME"  This is the port to access the pod.
  - name: newkubebastioncluster
    type: cluster
    integration: ship-kube #kubernetes account integartion name which have config file of master
    pointer:
      bastionHost:
        address: 52.34.32.118 #IP of 3rd instance (bastion) which is created in step 4
        user: ubuntu #bastionHost user this is deafult alwasy ubuntu
        keyIntegration: test-ssh   #resource name of the SSH key integrations in order to do that in shippable    # nodePort: <integer> # Port exposed on the node.  Kubernetes will auto-allocate by default.`     
  - name: test-ssh
    type: integration
    integration: test-ssh
jobs:
   - name: sn-provision
     type: provision
     steps:
       - IN: sn-img-1
       
  
  
   - name: test-provision
     type: provision
     on_start:                               # optional
      - NOTIFY: ship-slack
     steps:
       - IN: sn-gke-service-lb 
     on_success:                         # optional
       - NOTIFY: ship-slack         
     on_failure:                         # optional
       - NOTIFY: ship-slack         
     on_cancel:                              # optional
       - NOTIFY: ship-slack        
     #always:                             # optional
      # - NOTIFY: ship-slack   
   - name: test-provision-kube
     type: provision
     on_start:                               # optional
      - NOTIFY: ship-slack
     steps:
       - IN: newkubebastionloadbalancer
       - IN: test-ssh
     on_success:                         # optional
       - NOTIFY: ship-slack         
     on_failure:                         # optional
       - NOTIFY: ship-slack         
     on_cancel:                              # optional
       - NOTIFY: ship-slack     

        
        
        
